# Generated by Django 4.2.11 on 2024-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=150)),
                ('EmailAddress', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesaj yo',
            },
        ),
    ]
